### ISSUE TITLE
matplotlib syntax errors

### ISSUE THREAD

**Issue by itsa-mee-mario** [dylewsky/Data_Driven_Science_Python_Demos#8]
in Chapter 1, PCA ipynb, some lines contain syntax errors:
`ax2.plot(<plotting things here>,'-', Color="b", LineWidth=5)`
this raises an AttributeError and can be easily fixed by:
`ax2.plot(<plotting things here>,'-', c="b", lw=5)` or 
`ax2.plot(<plotting things here>,'-', color="b", linewidth=5)`

:)

**Comment by dylewsky** [comment]
This is the result of a deprecation in Matplotlib 3.3

Just pushed a fix, no warning should be raised now
